# Keras Application 응용
- 4가지 모델의 결과를 종합하여 결과 도출

In [2]:
from glob import glob
glob('animals/*')

['animals\\bear.jpg',
 'animals\\bird.jpg',
 'animals\\crocodile.jpg',
 'animals\\dolphin.jpg',
 'animals\\eagle.jpg',
 'animals\\elephant.jpg',
 'animals\\lion.jpg',
 'animals\\panda.jpg',
 'animals\\penguin.jpg',
 'animals\\rabbit.jpg']

In [3]:
name_list=[]
for file in glob('animals/*'):
    name = file.split('\\')[1].split('.')[0]
    name_list.append(name)
print(name_list)

['bear', 'bird', 'crocodile', 'dolphin', 'eagle', 'elephant', 'lion', 'panda', 'penguin', 'rabbit']


## All models and ensemble

In [1]:
from tensorflow.keras.applications.vgg16 import VGG16, decode_predictions
from tensorflow.keras.applications.vgg19 import VGG19
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.applications.resnet import ResNet101

import numpy as np 
from PIL import Image

In [7]:
vgg16 = VGG16()
vgg19 = VGG19()
resnet50 = ResNet50()
resnet101 = ResNet101()

In [26]:
img

array([[[178, 159, 145],
        [178, 159, 145],
        [178, 159, 145],
        ...,
        [188, 160, 146],
        [188, 160, 146],
        [188, 160, 146]],

       [[178, 159, 145],
        [178, 159, 145],
        [178, 159, 145],
        ...,
        [189, 161, 147],
        [189, 161, 147],
        [189, 161, 147]],

       [[178, 159, 145],
        [178, 159, 145],
        [178, 159, 145],
        ...,
        [192, 164, 150],
        [192, 164, 150],
        [192, 164, 150]],

       ...,

       [[191, 160, 139],
        [191, 160, 139],
        [191, 160, 139],
        ...,
        [194, 157, 139],
        [194, 157, 138],
        [194, 157, 138]],

       [[189, 158, 137],
        [193, 162, 141],
        [198, 167, 146],
        ...,
        [191, 154, 136],
        [191, 154, 135],
        [191, 154, 135]],

       [[197, 166, 145],
        [198, 167, 146],
        [200, 169, 148],
        ...,
        [187, 150, 131],
        [187, 150, 131],
        [187, 150, 131]]

In [10]:
file = 'animals/lion.jpg'
img = np.array(Image.open(file).resize((224,224)))
yhat_v16 = vgg16.predict(img.reshape(-1,224,224,3))
label = decode_predictions(yhat_v16)
label

[[('n02090721', 'Irish_wolfhound', 0.59328276),
  ('n02091831', 'Saluki', 0.26434946),
  ('n02092002', 'Scottish_deerhound', 0.06359713),
  ('n02090622', 'borzoi', 0.03421512),
  ('n02109047', 'Great_Dane', 0.016666468)]]

In [29]:
yhat_v16 = vgg16.predict(img.reshape((1,1000),224,224,3))
yhat_v16.shape

TypeError: 'tuple' object cannot be interpreted as an integer

In [34]:
yhat_v16[0]

array([7.15521045e-12, 4.63828325e-12, 1.56275382e-09, 2.22309934e-10,
       2.49762933e-10, 4.78525622e-11, 8.08529632e-11, 1.51569974e-08,
       5.43425305e-10, 1.70106923e-05, 7.00417391e-10, 3.46837614e-10,
       1.99969641e-09, 2.55677861e-08, 3.96018607e-10, 4.34651093e-10,
       1.29814337e-09, 9.77682024e-09, 8.52074244e-10, 9.55130641e-09,
       1.07005615e-09, 5.36380940e-09, 8.62982397e-09, 7.45769668e-08,
       2.25465556e-07, 9.26841763e-12, 5.74728182e-11, 3.33209467e-11,
       1.34174789e-11, 5.66423908e-10, 4.42975351e-10, 1.51570596e-11,
       4.49513732e-10, 5.52326296e-10, 1.60669469e-08, 1.89989951e-11,
       6.16397003e-11, 2.34077840e-12, 2.24216826e-10, 6.78938106e-09,
       3.88369309e-10, 1.30070366e-09, 4.19099144e-10, 9.37752453e-09,
       6.50407020e-11, 4.47301779e-11, 2.66276251e-10, 3.09541859e-09,
       1.05640019e-09, 6.43957665e-10, 1.11255083e-09, 2.90994051e-09,
       1.80689370e-11, 1.35170408e-11, 1.83310311e-10, 6.36978057e-12,
      

In [ ]:
yhat_v16[0]

In [12]:
label[0][0]

('n02090721', 'Irish_wolfhound', 0.59328276)

In [4]:
for file in glob('animals/*'):
    img = np.array(Image.open(file).resize((224,224)))
    yhat_v16 = vgg16.predict(img.reshape(-1,224,224,3))
img

array([[[204, 195, 190],
        [204, 195, 190],
        [204, 195, 190],
        ...,
        [215, 206, 201],
        [216, 207, 202],
        [216, 207, 202]],

       [[204, 195, 190],
        [204, 195, 190],
        [204, 195, 190],
        ...,
        [189, 180, 175],
        [190, 181, 176],
        [190, 181, 176]],

       [[204, 195, 190],
        [204, 195, 190],
        [204, 195, 190],
        ...,
        [190, 181, 176],
        [191, 182, 177],
        [191, 182, 177]],

       ...,

       [[151, 135, 120],
        [148, 132, 117],
        [142, 126, 111],
        ...,
        [ 37,  33,  19],
        [ 34,  30,  19],
        [ 40,  36,  29]],

       [[143, 127, 112],
        [142, 126, 111],
        [139, 123, 108],
        ...,
        [ 43,  39,  25],
        [ 46,  42,  31],
        [ 46,  41,  35]],

       [[137, 121, 106],
        [137, 121, 106],
        [136, 120, 105],
        ...,
        [ 45,  42,  28],
        [ 55,  51,  40],
        [ 50,  45,  38]]

In [ ]:
vgg16_list, vgg_list, resnet50_list, resnet101_list = [], [], [], []
ensemble = []

for file in glob('animals/*'):
    img = np.array(Image.open(file).resize((224,224)))
    yhat_v16 = vgg16.predict(img.reshape(-1,224,224,3))
    yhat_v19 = vgg19.predict(img.reshape(-1,224,224,3))
    yhat_r50 = resnet50.predict(img.reshape(-1, 224, 224, 3))
    yhat_v100 = resnet101.predict(img.reshape(-1, 224, 224, 3))

# 데이터 프레임으로 합치기

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'Original':name_list, 'VGG16':vgg16_list, 'VGG19':vgg19_list,
    'ResNet50':resnet50_list, 'ResNet101':resnet101_list, 'Ensemble':ensemble
})
df